name = "ccr"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = true
routes = [{ pattern = "ccr.duyet.net", custom_domain = true }]

[build]
command = "cargo install worker-build && worker-build --release"

# https://developers.cloudflare.com/workers/configuration/smart-placement/
[placement]
mode = "smart"

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1

# Environment variables
[vars]
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_MAX_TOKENS = "4096"
# OPENROUTER_API_KEY = "your-openrouter-api-key-here"  # Set via wrangler secret

# Local development environment variables
[env.local.vars]
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_MAX_TOKENS = "4096"
# For local dev, you can set OPENROUTER_API_KEY here temporarily
# OPENROUTER_API_KEY = "your-openrouter-api-key-here"
